### ISSUE TITLE
categorize rois

### ISSUE THREAD

**Issue by JonasCF** [abrazhe/image-funcut#15]
It would be fun, to group rois on neurons, astrocytes, neuropil ect.

**Comment by abrazhe** [comment]
Would you also try to elaborate on the ways of *how* to do that with regards of the user interface?

**Comment by JonasCF** [comment]
Eg a button 'add set of Rois' which creates a text input field, where you can add a string 'set name', that string should be added to the roi names. 
Works like this:
- add set of Rois
- enter 'n'
- place Rois: n-roi01, n-roi02 ect.
- add set of Rois
- enter 'a'
- place Rois: a-roi03, a-roi04 ect.

If each set should save as an individual file or in one file as a list of sets depends on the structure.
It would be cool , but not necessary to be able to Choose which sets to load.

Just the naming makes it easy, to know, what is what afterwards.
-

**Comment by abrazhe** [comment]
Should be closed by ae2757d8972f610673c2b12c5e710bf8b61ea964
