### ISSUE TITLE
Time series Export to mat

### ISSUE THREAD

**Issue by JonasCF** [abrazhe/image-funcut#24]
When exporting timeseries to mat, Changsi ask if some metadata could be included and if it could be created as a 3 dimentional array instead?

File should if possible contain  7 variables;

1)
ROI name = ('roi1','roi2'....'roi10')
2)
ROI all (3D array) = (number of frames) x (number of channels) x (number of ROIs)
3) 
ROI coordinates
4)
Frame rate
5)
GreenCh =  (number of rows) x (number of columns) x (number of frames)
6)
RedCh =  (number of rows) x (number of columns) x (number of frames)
7)
BlueCh =  (number of rows) x (number of columns) x (number of frames)

**Comment by abrazhe** [comment]
I'll add metadata from the frame sequence as a field, but I'll keep saving to `.mat`, because It's straightforward for me to do. Otherwise, it would be too many special cases in saving data.

**Comment by JonasCF** [comment]
It is great that you will save it as .mat, since this is what she needs. When she opens the timeseries.mat in matlab it holds 1 variable for each of the ROIs, she asked for a structure as above, but if it is to much work, I think that the most important improvement would be the metadata after stabilization.

**Comment by abrazhe** [comment]
Commit c66b1a42e08cb8b3ca60aadd0ff39c37c7859797  closes this issue. Meta information is now saved to `.mat` files.

Update with
```sh
pip install -U --no-deps https://github.com/abrazhe/image-funcut/archive/develop.zip
```

Usage in matlab:

```matlab
%load data 
x = load('test-rois.mat');

%access time interval between frames
dt = x.meta.axes(1)

%access first (e.g.) roi properties
label = x.roi_props{1}.label
place = x.roi_props{1}.center
radius = x.roi_props{1}.radius

%access data
x.ast01
```
This is the same format the data is saved into other formats, e.g. pickle. And this is the simplest for me to export to, because it requires minimal massaging of data. I am sure Changsi can convert this data to a format she likes in Matlab.
