### ISSUE TITLE
Average projection error after update

### ISSUE THREAD

**Issue by JonasCF** [abrazhe/image-funcut#25]
when I press h on a active frame nothing happens (same before)
when I press z (worked before), now;

Traceback (most recent call last):
  File "c:\Anaconda\lib\site-packages\matplotlib\backends\backend_wx.py", line 1
086, in _onKeyDown
    FigureCanvasBase.key_press_event(self, key, guiEvent=evt)
  File "c:\Anaconda\lib\site-packages\matplotlib\backend_bases.py", line 1833, i
n key_press_event
    self.callbacks.process(s, event)
  File "c:\Anaconda\lib\site-packages\matplotlib\cbook.py", line 540, in process

    proxy(*args, **kwargs)
  File "c:\Anaconda\lib\site-packages\matplotlib\cbook.py", line 415, in __call_
_
    return mtd(*args, **kwargs)
  File "c:\Anaconda\lib\site-packages\imfun\ui.py", line 1408, in frame_skip
    show_f = self.mean_frame
AttributeError: 'Picker' object has no attribute 'mean_frame'
Traceback (most recent call last):
  File "c:\Anaconda\lib\site-packages\matplotlib\backends\backend_wx.py", line 1
086, in _onKeyDown
    FigureCanvasBase.key_press_event(self, key, guiEvent=evt)
  File "c:\Anaconda\lib\site-packages\matplotlib\backend_bases.py", line 1833, i
n key_press_event
    self.callbacks.process(s, event)
  File "c:\Anaconda\lib\site-packages\matplotlib\cbook.py", line 540, in process

    proxy(*args, **kwargs)
  File "c:\Anaconda\lib\site-packages\matplotlib\cbook.py", line 415, in __call_
_
    return mtd(*args, **kwargs)
  File "c:\Anaconda\lib\site-packages\imfun\ui.py", line 1408, in frame_skip
    show_f = self.mean_frame
AttributeError: 'Picker' object has no attribute 'mean_frame'

**Comment by JonasCF** [comment]
Also when we load movies now they don't show in average projection, this is a very important feature for stefan while placing the ROIs

**Comment by abrazhe** [comment]
Fixed by commit 54ef8e592d350e7eeaf850e124897122ce188d8e Please update from the `develop` branch.

**Comment by JonasCF** [comment]
C:\Anaconda>pip install http://github.com/abrazhe/image-funcut/archive/develop.zip
Collecting http://github.com/abrazhe/image-funcut/archive/develop.zip
  Downloading http://github.com/abrazhe/image-funcut/archive/develop.zip
     - 167kB 375kB/s
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\anaconda\lib\site-packages (from image-funcut==0.2
.22)
Requirement already satisfied (use --upgrade to upgrade): scipy in c:\anaconda\lib\site-packages (from image-funcut==0.2
.22)
Collecting numba>=0.20.0 (from image-funcut==0.2.22)
  Downloading numba-0.22.1.tar.gz (873kB)
    100% |################################| 876kB 525kB/s
Requirement already satisfied (use --upgrade to upgrade): scikit-image>=0.11.0 in c:\anaconda\lib\site-packages (from im
age-funcut==0.2.22)
Requirement already satisfied (use --upgrade to upgrade): imreg in c:\anaconda\lib\site-packages (from image-funcut==0.2
.22)
Requirement already satisfied (use --upgrade to upgrade): dill>=0.2.4 in c:\anaconda\lib\site-packages (from image-funcu
t==0.2.22)
Requirement already satisfied (use --upgrade to upgrade): pathos>=0.1 in c:\anaconda\lib\site-packages (from image-funcu
t==0.2.22)
Requirement already satisfied (use --upgrade to upgrade): h5py>=2.5.0 in c:\anaconda\lib\site-packages (from image-funcu
t==0.2.22)
Requirement already satisfied (use --upgrade to upgrade): pandas>=0.16.0 in c:\anaconda\lib\site-packages (from image-fu
ncut==0.2.22)
Requirement already satisfied (use --upgrade to upgrade): traits>=4.4.0 in c:\anaconda\lib\site-packages (from image-fun
cut==0.2.22)
Requirement already satisfied (use --upgrade to upgrade): traitsui>=4.4.0 in c:\anaconda\lib\site-packages (from image-f
uncut==0.2.22)
Collecting wxpython (from image-funcut==0.2.22)
  Could not find a version that satisfies the requirement wxpython (from image-funcut==0.2.22) (from versions: )
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external wxpython to allow)
.
No matching distribution found for wxpython (from image-funcut==0.2.22)

C:\Anaconda>

**Comment by abrazhe** [comment]
I have to admit I still can't get the automatic handling of dependencies right. For now, use the command below to update:

```bash
pip install --no-deps -U https://github.com/abrazhe/image-funcut/archive/develop.zip 
```
