### ISSUE TITLE
Choosing correct directory when exporting vessel diameters

### ISSUE THREAD

**Issue by ChangsiCai** [abrazhe/image-funcut#9]
1. The figure 'lines' and 'r01','r02' etc. should be saved in the same folder of 'Export vessel Diameter'. But now 'lines' and 'r0*' are saved in the open fig path.

2. Location of each lines can be saved in mat/csv files as well.

**Comment by abrazhe** [comment]
as to the second question, I'll add these links here so I don't forget:

  1. http://xcorr.net/2013/06/12/load-pickle-files-in-matlab/
  2. http://stackoverflow.com/questions/25859968/in-matlab-how-to-read-python-pickle-file

**Comment by abrazhe** [comment]
Closed by commit fadee953f9483524101bdd3e7a7c37eeb3016c54 to develop
